name: Run Tests for bundle against Change

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - name: List changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV
      - name: Retrieve Scripts
        run: |
          git clone https://github.com/forcedotcom/bundle-publish-scripts.git
      - name: Update for Publishing
        run: |
          node bundle-publish-scripts/scripts/updateForCoreBundle.js
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: Run Tests within the Project
        run: |
          yarn test